#!/bin/bash

set -e -u

# Set working directory to the root of the repo, so the script can be run from
# any location.
cd "$(dirname $0)/.."

if [[ $# -ne 2 ]]; then
	echo "usage: $0 context token" >&2
	exit 1
fi
context=$1
token=$2

docker --context "${context}" rm -f anololcatbot
docker --context "${context}" run -d --restart always --name anololcatbot \
	-e "ANOLOLCATBOT_TOKEN=${token}" anololcatbot
